baseurl = "https://hannahlKIT.github.io/hannahs_blog/"
title = "Life of Lorena"
theme = "hugo-theme-cleanwhite"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
preserveTaxonomyNames = true
hasCJKLanguage = false

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    title = "Life of Lorena"
    [languages.en.params]
      SEOTitle = "Life of Lorena"
      description = "Hannah Lorenas personal blog"
      keyword = "blog, Hannah Lorena, journalism, travel"
      slogan = "My thoughts, work and everything else"
      sidebar_about_description = "About me"
    [[languages.en.params.additional_menus]]
      title = "ARCHIVE"
      href  = "archive/"
    [[languages.en.params.additional_menus]]
      title = "ABOUT"
      href  = "about/"

  [languages.de]
    languageName = "Deutsch"
    languageCode = "de-de"
    weight = 2
    title = "Life of Lorena"
    contentDir = "content"
    [languages.de.params]
      SEOTitle = "Life of Lorena"
      description = "Hannah Lorenas persönlicher Blog"
      keyword = "Blog, Hannah Lorena, Journalismus, Reisen"
      slogan = "My thoughts, work and everything else"
      sidebar_about_description = "Über mich"
    [[languages.de.params.additional_menus]]
      title = "ARCHIV"
      href  = "archive/"
    [[languages.de.params.additional_menus]]
      title = "ÜBER"
      href  = "about/"

[services]
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 5

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/Header_sitzend.JPG"
  upstreamAttribution = false

  dark_mode_toggle = false
  auto_theme = false

  image_404 = "img/404-bg.jpg"
  title_404 = "Page not found :("
  omit_categories = false

  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  sidebar_avatar = "img/Profilbild.JPG"

  featured_tags = true
  featured_condition_size = 1

  ba_track_id = ""
  disqus_proxy = ""
  disqus_site = ""
  twikoo_env_id = ""

  artalk_enable = false
  artalk_server = ""
  artalk_site = ""

  reward = false

  friends = false
  bookmarks = false
  about_me = true

  last_posts = true

  [params.social]
  rss            = true
  email          = "hstaus@gmx.com"
  github         = "https://github.com/YOUR_GITHUB_USERNAME"
  #linkedin      = "https://www.linkedin.com/in/hannah-staus-2020/"
  #instagram     = "full profile url in instagram"
  #twitter       = "full profile url in twitter"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']
